# Generated by Django 4.2.1 on 2023-05-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClothingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('color', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('Верхняя одежда', 'Верхняя одежда'), ('Брюки', 'Брюки'), ('Обувь', 'Обувь')], max_length=20)),
                ('material', models.CharField(choices=[('Хлопок', 'Хлопок'), ('Деним', 'Деним'), ('Шерсть', 'Шерсть')], max_length=20)),
                ('vid', models.CharField(max_length=100)),
            ],
        ),
    ]
